---
# defaults file for ansible-role-traefik

# Directory where Traefik compose files and .env reside on the target host
traefik_dir: "/opt/traefik"

# --- Files ---
# Name of the compose file
traefik_compose_filename: "docker-compose.yml"
# Full path to the compose file
traefik_compose_file: "{{ traefik_dir }}/{{ traefik_compose_filename }}"

# Name of the environment file
traefik_env_filename: ".env"
# Full path to the environment file
traefik_env_file: "{{ traefik_dir }}/{{ traefik_env_filename }}"

# Set to true if Ansible should template these files instead of checking existence
traefik_template_env_file: false
traefik_template_compose_file: false
# Source template paths (used if traefik_template_* is true)
traefik_env_template: "traefik.env.j2"
traefik_compose_template: "docker-compose.yml.j2"

# --- Docker ---
# Name of the Docker Compose project (used for container/network naming prefix)
traefik_project_name: "traefik"
# Expected name of the Traefik container (often depends on project name and service name in compose)
traefik_container_name: "{{ traefik_project_name }}-traefik-1" # Adjust if service name isn't 'traefik'

# List of Docker networks required by Traefik or its services
traefik_required_networks:
  - traefik_proxy # Example network name

# --- Health Check ---
# Max retries for health check
traefik_health_retries: 30
# Delay between health check retries (in seconds)
traefik_health_delay: 2
# Number of log lines to show if health check fails
traefik_log_lines_on_fail: 20