---
galaxy_info:
  role_name: wordpress_project
  author: Your Name
  description: Create a full Wordpress project (compose/.env/docker-compose.yml) managed by Traefik.
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
dependencies: []
