- name: Harden server security
  hosts: all
  become: yes
  tasks:
    - name: Update system
      apt: update_cache=yes upgrade=dist

    - name: Install UFW firewall
      apt:
        name: ufw
        state: present

    - name: Allow SSH and HTTP
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 22
        - 80
        - 443

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny

    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
